// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A commission price suggestion AI agent.
 *
 * - suggestCommissionPrice - A function that suggests a commission price.
 * - SuggestCommissionPriceInput - The input type for the suggestCommissionPrice function.
 * - SuggestCommissionPriceOutput - The return type for the suggestCommissionPrice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestCommissionPriceInputSchema = z.object({
  skills: z
    .string()
    .describe('The skills of the freelancer.'),
  experienceYears: z.number().describe('The years of experience of the freelancer.'),
  marketTrends: z.string().describe('The current market trends for the service.'),
});
export type SuggestCommissionPriceInput = z.infer<typeof SuggestCommissionPriceInputSchema>;

const SuggestCommissionPriceOutputSchema = z.object({
  suggestedPrice: z.number().describe('The suggested commission price.'),
  reasoning: z.string().describe('The reasoning behind the suggested price.'),
});
export type SuggestCommissionPriceOutput = z.infer<typeof SuggestCommissionPriceOutputSchema>;

export async function suggestCommissionPrice(input: SuggestCommissionPriceInput): Promise<SuggestCommissionPriceOutput> {
  return suggestCommissionPriceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestCommissionPricePrompt',
  input: {schema: SuggestCommissionPriceInputSchema},
  output: {schema: SuggestCommissionPriceOutputSchema},
  prompt: `You are an expert in pricing freelance services. Based on the freelancer's skills, experience, and current market trends, you will suggest a competitive commission price.

Skills: {{{skills}}}
Experience (Years): {{{experienceYears}}}
Market Trends: {{{marketTrends}}}

Consider all these factors and return the suggested price and the reasoning behind it.
`,
});

const suggestCommissionPriceFlow = ai.defineFlow(
  {
    name: 'suggestCommissionPriceFlow',
    inputSchema: SuggestCommissionPriceInputSchema,
    outputSchema: SuggestCommissionPriceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
